apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
    spec:
      containers:
        - name: svc-a
          image: ccr.ccs.tencentyun.com/k8s-env/svc-a:v1
          ports:
            - containerPort: 8080
          env:
          - name: HOST
            value: http://service-b